### ISSUE TITLE
Transferring ownership of this repository- to whom?

### ISSUE THREAD

**Issue by dgrtwo** [milesrichardson/ParsePy#141]
Hello,

I am no longer interested in maintaining or owning this repository. This has no reflection on the project or its contributors- it is simply because I've moved from working primarily in Python to working in R.

Of course anyone is welcome to fork this repo and call theirs the active one, but this particular repo does come with a number of stars/watchers/issues that are unfairly drawing attention. I would thus like to transfer this repo (along with its stars, watchers, etc) to someone committed to its active and continuing development.

I've tagged several people with active forks or who have been active in this development, but this conversation is open to anyone who has contributed in any way. Let's decide together where it should be transferred. I am entirely happy to transfer it to an organization- I am simply not well educated enough about the Parse ecosystem to know where it belongs.

If there are multiple volunteers for taking the repo who can't resolve it among themselves, I'll pick a neutral metric to "break the tie". In absence of a better metric, I'd suggest number of commits + closed issues in the last year. In any case, if you'd like to volunteer for ownership or share your thoughts on where it should go, please do so before **12 PM EST Friday, May 13**

I certainly hope this project will continue to be maintained and be useful. Thank you all for your contributions!

@milesrichardson

@lebouquetin

@basilfamer

@lullis

@mcastle 

@farin 

@amitmalhotra

@deeGraYve

@danrobinson

**Comment by dgrtwo** [comment]
I should note that the suggestion in #140 to transfer the repo to ParsePlatform sounds like a good idea to me. But in that case we should decide who wants/gets commit rights. And again, I am not nearly up-to-date enough about this platform to make a unilateral decision.

**Comment by milesrichardson** [comment]
I am still using this library every day (along with self hosted parse-server) and would be happy to take it over. I have no preference whether you transfer it to me personally or to ParsePlatform and give me commit rights. If you transfer to ParsePlatform, the advantage is you could easily give commit rights to more than just me.

**Comment by Sadmansamee** [comment]
#140 's idea seems to be  nice way to commit in parse server repo, this repo can be added to Parse-server repo and this should continue.

**Comment by dgrtwo** [comment]
Many thanks to @milesrichardson for volunteering! I have changed the name and email in setup.py to reflect this and given you commit rights immediately.

I agree it's best the repo get transferred to ParsePlatform, but I don't believe I can do so without admin rights in that organization, and I don't know whom to contact. In the meantime to speed things along I'd like to transfer it to Miles, so that I can stop being a blocking step in this process.

**Comment by dgrtwo** [comment]
(To do so @milesrichardson I think you'd have to take your fork offline. Of course you're free to merge any changes in after the fact. If you know a fast way to transfer this to ParsePlatform I'm also happy to do so).

**Comment by milesrichardson** [comment]
@dgrtwo ok, Unforked

**Comment by milesrichardson** [comment]
@gfosco Can we transfer ownership of this repo to ParsePlatform? see thread

**Comment by gfosco** [comment]
I don't think we're interested in taking ownership of it, so I think it's in good hands with @milesrichardson.

**Comment by dgrtwo** [comment]
Works for me. Good luck @milesrichardson!

Let me know if you need anything else from me but all decisions henceforth are yours and/or other active contributors.
