### ISSUE TITLE
register without having a REST_API_KEY

### ISSUE THREAD

**Issue by lancdec** [milesrichardson/ParsePy#154]
It is my understanding that the REST_API_KEY is not longer required for parse server. Therefore is it possible to not require a REST_API_KEY much like the master key is optional? 

I have resolved this issue by setting 

REST_API_KEY = None

This satisfies the need for three parameters in the register function call even though the rest key is not used.

**Comment by milesrichardson** [comment]
Hey, sorry just seeing this -- glad you got it resolved - I was going to suggest the same :)
