### ISSUE TITLE
parse-py not pointing to the self-hosted server 

### ISSUE THREAD

**Issue by myopicdoll** [milesrichardson/ParsePy#159]
Even after setting the env var parsePy doesn't seem to be pointing to self-hosted server based on logs.

```
root = config.get('parse-db-prod', 'uri_root')
os.environ["PARSE_API_ROOT"] = root

print os.environ.get("PARSE_API_ROOT") # shows the right uri
```

in a long running batch job it spits out this error:

`parse_rest.core.ParseError: {"code":2,"error":"the service is currently unavailable"}`

**Comment by milesrichardson** [comment]
Hi

You must set the environment variable *before* importing any ParsePy modules (either above your `import` statements, or within your environment before calling the script).

Hope that helps

**Comment by myopicdoll** [comment]
Thanks! That worked like a charm. I was importing a couple error stuff from ParsePy query prior to setting the environment variable.
