### ISSUE TITLE
Ability to access config options.

### ISSUE THREAD

**Issue by cdriehuys** [milesrichardson/ParsePy#161]
Is there any way to access the config options on a parse application? On the online dashboard they are available in the *Config* tab in the sidebar. If this is not implemented, I would be happy to look into it. For reference, the docs for accessing these attributes through the REST API are [here](https://parseplatform.github.io/docs/rest/guide/#config).

**Comment by milesrichardson** [comment]
@cdriehuys 

Hi Chathan,

Sorry for the late reply, I've been traveling.

Currently `GET` requests for `/config` are implemented. I haven't tested it myself but it looks like it should work.

Here is the relevant file:

https://github.com/milesrichardson/ParsePy/blob/67a7042a19885dbe4d7f845257bfefa5fc9332ab/parse_rest/config.py

If you would like to implement `POST` requests as well (for setting config values), please feel free to submit a PR. The code should be pretty straight forward.

Miles

**Comment by cdriehuys** [comment]
Sorry for the late response, I've also been traveling. Thank you for the info. I believe `GET` requests are all I need at the moment, but if I ever need to update config values I'll be sure to submit a PR.
