### ISSUE TITLE
Batch save isn't working properly

### ISSUE THREAD

**Issue by teehamaral** [milesrichardson/ParsePy#171]
The method `execute` is not receiving `batch=True` as an argument to handle this, so I think that isn't working as a batch process itself.

https://github.com/milesrichardson/ParsePy/blob/master/parse_rest/connection.py#L189

**Comment by black-puppydog** [comment]
hehe, lost interest? 😁

**Comment by teehamaral** [comment]
Yep, seems that's not relavant anymore 😄
