### ISSUE TITLE
Trouble Registering With Bitnami Parse-Server AWS Image

### ISSUE THREAD

**Issue by michaelyma12** [milesrichardson/ParsePy#178]
Hello,

I am presently trying to connect to the parse-server instance from my [Bitnami Parse-Server AWS Image](https://aws.amazon.com/marketplace/pp/B01BLQ17TO). 

However, I noticed the `register() ` function requires a `rest_key` parameter. To get this, I went to the `/opt/bitnami/apps/parse/htdocs/server.js` file in the image, and saw the following variables:

```
var api = new ParseServer({
    databaseURI: "mongodb://root:WcbKujWVdiX2@127.0.0.1:27017/bitnami_parse",
    cloud: "./node_modules/parse-server/lib/cloud-code/Parse.Cloud.js",
    appId: "APP_ID",
    masterKey: "MASTER_KEY",
    fileKey: "FILE_KEY",
    serverURL: "http://34.242.164.250:80/parse"
});
```

I tried passing both the masterKey and fileKey variables as the `rest_key` argument for the function, and received the following error in both instances:

```
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/parse_rest/connection.py", line 140, in execute
    response = urlopen(request, timeout=CONNECTION_TIMEOUT)
  File "/anaconda3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/anaconda3/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/anaconda3/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/anaconda3/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/anaconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/anaconda3/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 410: Parse.com has shutdown - https://parseplatform.github.io/
```

I also tried adding a `restAPIKey` argument in the `server.js` file above, rebooting my instance, and then passing it in as the arg. Unfortunately, that led to no difference in result. 

Any guidance would be appreciated, thanks.

**Comment by milesrichardson** [comment]
hi @michaelyma12 

This is a parse-server issue. You need to instantiate parse-server with options including `restApiKey`. 

https://github.com/parse-community/parse-server#client-key-options
